name: hola-mundo
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: run-hola-mundo
        run: |
          python saludo.py
